openapi: "3.0.0"
info:
  version: 1.0.0
  title: Pikerando API
paths:
  /groupOrders:
    get:
      summary: List all GroupOrders
      operationId: listGroupOrders
      tags:
        - groupOrders
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of GroupOrders
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GroupOrderTo"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorTo"
    post:
      summary: Create an groupOrder
      operationId: createGroupOrder
      tags:
        - groupOrders
      requestBody:
        description: the groupOrder properties
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GroupOrderTo"

      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorTo"
  /groupOrders/{groupOrderId}:
    get:
      summary: Info for a specific groupOrder
      operationId: showGroupOrderById
      tags:
        - groupOrders
      parameters:
        - name: groupOrderId
          in: path
          required: true
          description: The id of the groupOrder to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ItemTo"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorTo"


  /groupOrders/{groupOrderId}/itmes:
    post:
        summary: Create an item
        operationId: createItem
        tags:
          - groupOrders
        parameters:
          - name: groupOrderId
            in: path
            required: true
            description: The id of the GroupOrder to retrieve
            schema:
              type: string
        requestBody:
          description: the item properites
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemTo"

        responses:
          '201':
            description: Null response
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorTo"
components:
  schemas:
    GroupOrderTo:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ItemTo:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ErrorTo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string